package br.com.eduardo.mscustomer.validCustomer.model

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "customer")
class Customer(
    @field:DynamoDBAttribute
    val fantasyName: String
) {
    @field:DynamoDBHashKey
    @field:DynamoDBAutoGeneratedKey
    var id: String? = null
}
